AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.9
      Handler: app.lambda_handler
      CodeUri: s3://tsetbucketforsamprajwaltestabc123/ec247cb83ce6d8a0dd4dbd52cabfe0e3
      MemorySize: 128
      Timeout: 3
      Environment:
        Variables:
          TABLE_NAME:
            Ref: Table
          REGION_NAME:
            Ref: AWS::Region
      Description: a starter function.
      Events:
        MyEvent:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: Table
  Table:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: greeting
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
